export const destructuredTheme = ({
	color: { black, white, grey, blue, purple, gradient, gradient2 },
	font: { lato, oxygen },
	fontSize: { lg10, md5, sm1 },
	opacity: { op70 },
	borderRadius: { br50 },
	padding: { p2 },
	thickness: { thick2 },
}) => ({
	black,
	white,
	grey,
	blue,
	purple,
	gradient,
	gradient2,
	lato,
	oxygen,
	lg10,
	md5,
	sm1,
	op70,
	br50,
	p2,
	thick2,
});